#!/bin/bash

runjobs ICLISTENER DAILY; runjobs ICUSGMGR ICMON; 
runjobs ICRTDEF ICRTDEF; runjobs ICRT001 ICRT001; runjobs ICRT003 ICRT003; runjobs ICRT005 ICRT005;
runjobs UPRTUSAGE DAILY; runjobs UPRTUSAGE1 UPRTUSAGE1; runjobs UPRTUSAGE3 UPRTUSAGE3; runjobs UPRTUSAGE5 UPRTUSAGE5;